adminlte.settings:
  type: theme_settings
  label: 'AdminLTE settings'
  mapping:
    default_color_mode:
      type: string
      label: 'Default colour mode'
    sidebar_dark:
      type: boolean
      label: 'Dark sidebar'
