adminlte.settings:
  type: theme_settings
  label: 'AdminLTE settings'
  mapping:
    default_color_mode:
      type: string
      label: 'Default colour mode'
    sidebar_dark:
      type: boolean
      label: 'Dark sidebar'
    sidebar_collapsed:
      type: boolean
      label: 'Start with the sidebar collapsed'
    compact_mode:
      type: boolean
      label: 'Compact mode'
    force_rtl:
      type: boolean
      label: 'Force right-to-left (RTL) layout'
    primary_color:
      type: string
      label: 'Primary (accent) colour'
